
[light_sources]
	entities = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				item = true
				tnt_minecart = true
				minecart = true
				furnace_minecart = true
				creeper = true
				skeleton = true
				zombie = true
				bat = true
				cod = true
				tropical_fish = true
				spider = true
				glow_squid = true
				squid = true
				witch = true
				chicken = true
				drowned = true
				pufferfish = true
				pig = true
				parrot = true
				bee = true
				enderman = true
				zombie_villager = true
				salmon = true
				rabbit = true
				husk = true
				axolotl = true
				wolf = true
				turtle = true
				armor_stand = true
				vindicator = true
				evoker = true
				iron_golem = true
				villager = true
				cat = true
				painting = true
				cow = true
				dolphin = true
				experience_orb = true

			[light_sources.settings.entities.betteranimalsplus]
				badger = true
				pheasant = true
				deer = true
				shark = true
				octopus = true
				flying_fish = true
				whale = true
				jellyfish = true
				feralwolf = true
				butterfly = true
				piranha = true
				songbird = true
				turkey = true
				goose = true
				boar = true
				coyote = true
				lamprey = true
				eel_freshwater = true
				nautilus = true
				squirrel = true
				crab = true
				horseshoecrab = true
				barracuda = true
				eel_saltwater = true

			[light_sources.settings.entities.mobz]
				friend = true
				armored = true
				tspider = true
				skeli4 = true
				dwarf = true
				skeli2 = true
				fast = true
				slimo = true
				boar = true
				tank = true
				mage2 = true
				spo = true
				gchicken = true
				boar3 = true
				crip = true
				brownbear = true
				fulliron = true
				spi = true
				knight2 = true
				knight4 = true
				knight = true

			[light_sources.settings.entities.whisperwoods]
				moth = true
				zotzpyre = true
				wisp = true

			[light_sources.settings.entities.graveyard]
				ghoul = true
				revenant = true
				skeleton_creeper = true

			[light_sources.settings.entities.earth]
				rubro = true
				pertilyo = true

			[light_sources.settings.entities.terrarianslimes]
				green_slime = true
				black_slime = true
				yellow_slime = true
				jungle_slime = true
				sand_slime = true
				mother_slime = true
				red_slime = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

			[light_sources.settings.entities.adventurez]
				amethyst_golem = true
				iguana = true

			[light_sources.settings.entities.elementalcreepers]
				illusion_creeper = true
				cookie_creeper = true
				light_creeper = true
				water_creeper = true
				firework_creeper = true
				electric_creeper = true
				dark_creeper = true

			[light_sources.settings.entities.myloot]
				loot_chest_minecart = true

			[light_sources.settings.entities.bewitchment]
				ghost = true

			[light_sources.settings.entities.valley]
				perch = true

